<?php

namespace Craft\Core\Component;

use Bitrix\Main\Page\Asset;
use Craft\Core\Exceptions\Component\CaptchaValidateException;
use Craft\Core\Html\Html;
use Craft\Core\Component\Security\Captcha;

abstract class CaptchaComponent extends HtmlComponent
{
	public function onPrepareComponentParams($arParams)
	{
		$arParams = parent::onPrepareComponentParams($arParams); // TODO: Change the autogenerated stub

		$arParams['USE_CAPTCHA'] = in_array($arParams['USE_CAPTCHA'], ['Y', 'N']) ? $arParams['USE_CAPTCHA'] : 'N';

		return $arParams;
	}

	public function captcha(): string
	{
		if(!$this->isEnabledCaptcha())
		{
			return '';
		}

		Asset::getInstance()->addJs('https://smartcaptcha.yandexcloud.net/captcha.js');

		$html = Html::beginTag('div', [
			'id'           => 'captcha-container',
			'class'        => 'smart-captcha',
			'data-sitekey' => SMARTCAPTCHA_CLIENT_KEY,
		]);
		$html .= Html::endTag('div');

		return $html;
	}


	protected function validateCaptcha(array $postData): void
	{
		if(!$this->isEnabledCaptcha())
		{
			return;
		}

		if(!Captcha::validateCaptcha($postData['smart-token']))
		{
			throw new CaptchaValidateException();
		}
	}

	private function isEnabledCaptcha(): bool
	{
		return $this->arParams['USE_CAPTCHA'] == 'Y' && defined('SMARTCAPTCHA_CLIENT_KEY');
	}
}